defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .


scan:
  # loader: 'camera_geometry'
  loader: 'synthetic'
  scan_paths:
    # - /home/casey/Uni/data/plant_and_food/tonemapped/2022-08-31/jpeg_north_resized/refined_5cm.json
    - /home/casey/PhD/data/nerf_datasets/nerf_synthetic/lego
  scan_pose_paths:
    - null
  frame_ranges:
    - null
  frame_strides:
    - null
  image_scale: 1
  bound: 4

log:
  root_dir: './neus/logs/synthetic/test2'
  eval_image_freq: end
  eval_pointcloud_freq: null
  save_weights_freq: null

trainer:
  num_epochs: 10
  iters_per_epoch: 33
  n_rays: 1024

renderer:
  steps:
    - 256
  z_bounds:
    - 2
    - 6
  importance_steps: 128
  alpha: 0.2

optimizer:
  encoding:
    lr: 2e-2
  latent_emb:
    lr: 2e-2
  net:
    weight_decay: 1e-6
    lr: 1e-3
  betas:
    - 0.9
    - 0.99
  eps: 1e-15

scheduler: step

nerf_init:
  path: null

nets:
  encoding:
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 24
    precision: float32
  
  encoding_dir:
    encoding: SphericalHarmonics
    degree: 4
    precision: float32

  latent_embedding:
    features: 48

  sigma:
    num_layers: 2
    hidden_dim: 64
    geo_feat_dim: 15

  color:
    num_layers: 3
    hidden_dim: 64